/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Amount { 'amount' : bigint }
export interface TopUpRequest {
  'id' : TopUpRequestId,
  'status' : { 'pending' : null } |
    { 'completed' : null },
  'payoutIdentifier' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'amount' : Amount,
  'paymentProvider' : { 'imePay' : null } |
    { 'khalti' : null },
  'transactionId' : string,
}
export type TopUpRequestId = Principal;
export type TournamentId = Principal;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WalletTransaction {
  'id' : WalletTransactionId,
  'transactionType' : { 'withdrawalRequest' : null } |
    { 'topUp' : null } |
    { 'deposit' : null } |
    { 'withdrawal' : null } |
    { 'prize' : null },
  'userId' : Principal,
  'createdAt' : bigint,
  'amount' : Amount,
}
export type WalletTransactionId = Principal;
export interface WithdrawalRequest {
  'id' : WithdrawalRequestId,
  'status' : { 'pending' : null } |
    { 'completed' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'payoutIdentifier' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'amount' : Amount,
  'payoutName' : string,
  'paymentProvider' : { 'imePay' : null } |
    { 'khalti' : null },
}
export type WithdrawalRequestId = Principal;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveTopUpRequest' : ActorMethod<[TopUpRequestId], undefined>,
  'approveWithdrawalRequest' : ActorMethod<[WithdrawalRequestId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTopUpRequest' : ActorMethod<[Amount], TopUpRequestId>,
  'createTournament' : ActorMethod<[string, Amount], TournamentId>,
  'getBalance' : ActorMethod<[], Amount>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTopUpHistory' : ActorMethod<[], Array<TopUpRequest>>,
  'getTopUpRequests' : ActorMethod<[], Array<TopUpRequest>>,
  'getTransactionHistory' : ActorMethod<[], Array<WalletTransaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinTournament' : ActorMethod<[TournamentId], boolean>,
  'markWithdrawalRequestCompleted' : ActorMethod<
    [WithdrawalRequestId],
    undefined
  >,
  'requestWithdrawal' : ActorMethod<
    [Amount, { 'imePay' : null } | { 'khalti' : null }, string, string],
    WithdrawalRequestId
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'verifyTournament' : ActorMethod<[TournamentId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];