/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TopUpRequestId = IDL.Principal;
export const WithdrawalRequestId = IDL.Principal;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Amount = IDL.Record({ 'amount' : IDL.Int });
export const TournamentId = IDL.Principal;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TopUpRequest = IDL.Record({
  'id' : TopUpRequestId,
  'status' : IDL.Variant({ 'pending' : IDL.Null, 'completed' : IDL.Null }),
  'payoutIdentifier' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'amount' : Amount,
  'paymentProvider' : IDL.Variant({ 'imePay' : IDL.Null, 'khalti' : IDL.Null }),
  'transactionId' : IDL.Text,
});
export const WalletTransactionId = IDL.Principal;
export const WalletTransaction = IDL.Record({
  'id' : WalletTransactionId,
  'transactionType' : IDL.Variant({
    'withdrawalRequest' : IDL.Null,
    'topUp' : IDL.Null,
    'deposit' : IDL.Null,
    'withdrawal' : IDL.Null,
    'prize' : IDL.Null,
  }),
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'amount' : Amount,
});
export const WithdrawalRequest = IDL.Record({
  'id' : WithdrawalRequestId,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'payoutIdentifier' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'amount' : Amount,
  'payoutName' : IDL.Text,
  'paymentProvider' : IDL.Variant({ 'imePay' : IDL.Null, 'khalti' : IDL.Null }),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveTopUpRequest' : IDL.Func([TopUpRequestId], [], []),
  'approveWithdrawalRequest' : IDL.Func([WithdrawalRequestId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTopUpRequest' : IDL.Func([Amount], [TopUpRequestId], []),
  'createTournament' : IDL.Func([IDL.Text, Amount], [TournamentId], []),
  'getBalance' : IDL.Func([], [Amount], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTopUpHistory' : IDL.Func([], [IDL.Vec(TopUpRequest)], ['query']),
  'getTopUpRequests' : IDL.Func([], [IDL.Vec(TopUpRequest)], ['query']),
  'getTransactionHistory' : IDL.Func(
      [],
      [IDL.Vec(WalletTransaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinTournament' : IDL.Func([TournamentId], [IDL.Bool], []),
  'markWithdrawalRequestCompleted' : IDL.Func([WithdrawalRequestId], [], []),
  'requestWithdrawal' : IDL.Func(
      [
        Amount,
        IDL.Variant({ 'imePay' : IDL.Null, 'khalti' : IDL.Null }),
        IDL.Text,
        IDL.Text,
      ],
      [WithdrawalRequestId],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'verifyTournament' : IDL.Func([TournamentId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TopUpRequestId = IDL.Principal;
  const WithdrawalRequestId = IDL.Principal;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Amount = IDL.Record({ 'amount' : IDL.Int });
  const TournamentId = IDL.Principal;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TopUpRequest = IDL.Record({
    'id' : TopUpRequestId,
    'status' : IDL.Variant({ 'pending' : IDL.Null, 'completed' : IDL.Null }),
    'payoutIdentifier' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'amount' : Amount,
    'paymentProvider' : IDL.Variant({
      'imePay' : IDL.Null,
      'khalti' : IDL.Null,
    }),
    'transactionId' : IDL.Text,
  });
  const WalletTransactionId = IDL.Principal;
  const WalletTransaction = IDL.Record({
    'id' : WalletTransactionId,
    'transactionType' : IDL.Variant({
      'withdrawalRequest' : IDL.Null,
      'topUp' : IDL.Null,
      'deposit' : IDL.Null,
      'withdrawal' : IDL.Null,
      'prize' : IDL.Null,
    }),
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'amount' : Amount,
  });
  const WithdrawalRequest = IDL.Record({
    'id' : WithdrawalRequestId,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'payoutIdentifier' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'amount' : Amount,
    'payoutName' : IDL.Text,
    'paymentProvider' : IDL.Variant({
      'imePay' : IDL.Null,
      'khalti' : IDL.Null,
    }),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveTopUpRequest' : IDL.Func([TopUpRequestId], [], []),
    'approveWithdrawalRequest' : IDL.Func([WithdrawalRequestId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTopUpRequest' : IDL.Func([Amount], [TopUpRequestId], []),
    'createTournament' : IDL.Func([IDL.Text, Amount], [TournamentId], []),
    'getBalance' : IDL.Func([], [Amount], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTopUpHistory' : IDL.Func([], [IDL.Vec(TopUpRequest)], ['query']),
    'getTopUpRequests' : IDL.Func([], [IDL.Vec(TopUpRequest)], ['query']),
    'getTransactionHistory' : IDL.Func(
        [],
        [IDL.Vec(WalletTransaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinTournament' : IDL.Func([TournamentId], [IDL.Bool], []),
    'markWithdrawalRequestCompleted' : IDL.Func([WithdrawalRequestId], [], []),
    'requestWithdrawal' : IDL.Func(
        [
          Amount,
          IDL.Variant({ 'imePay' : IDL.Null, 'khalti' : IDL.Null }),
          IDL.Text,
          IDL.Text,
        ],
        [WithdrawalRequestId],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'verifyTournament' : IDL.Func([TournamentId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };