/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Amount {
    amount: bigint;
}
export type WithdrawalRequestId = Principal;
export type TopUpRequestId = Principal;
export interface WalletTransaction {
    id: WalletTransactionId;
    transactionType: Variant_withdrawalRequest_topUp_deposit_withdrawal_prize;
    userId: Principal;
    createdAt: bigint;
    amount: Amount;
}
export interface WithdrawalRequest {
    id: WithdrawalRequestId;
    status: Variant_pending_completed_approved_rejected;
    payoutIdentifier: string;
    userId: Principal;
    createdAt: bigint;
    amount: Amount;
    payoutName: string;
    paymentProvider: Variant_imePay_khalti;
}
export interface TopUpRequest {
    id: TopUpRequestId;
    status: Variant_pending_completed;
    payoutIdentifier: string;
    userId: Principal;
    createdAt: bigint;
    amount: Amount;
    paymentProvider: Variant_imePay_khalti;
    transactionId: string;
}
export type WalletTransactionId = Principal;
export interface UserProfile {
    name: string;
}
export type TournamentId = Principal;
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_imePay_khalti {
    imePay = "imePay",
    khalti = "khalti"
}
export enum Variant_pending_completed {
    pending = "pending",
    completed = "completed"
}
export enum Variant_pending_completed_approved_rejected {
    pending = "pending",
    completed = "completed",
    approved = "approved",
    rejected = "rejected"
}
export enum Variant_withdrawalRequest_topUp_deposit_withdrawal_prize {
    withdrawalRequest = "withdrawalRequest",
    topUp = "topUp",
    deposit = "deposit",
    withdrawal = "withdrawal",
    prize = "prize"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveTopUpRequest(topUpRequestId: TopUpRequestId): Promise<void>;
    approveWithdrawalRequest(withdrawalRequestId: WithdrawalRequestId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createTopUpRequest(amount: Amount): Promise<TopUpRequestId>;
    createTournament(name: string, entryFee: Amount): Promise<TournamentId>;
    getBalance(): Promise<Amount>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getTopUpHistory(): Promise<Array<TopUpRequest>>;
    getTopUpRequests(): Promise<Array<TopUpRequest>>;
    getTransactionHistory(): Promise<Array<WalletTransaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWithdrawalRequests(): Promise<Array<WithdrawalRequest>>;
    isCallerAdmin(): Promise<boolean>;
    joinTournament(tournamentId: TournamentId): Promise<boolean>;
    markWithdrawalRequestCompleted(withdrawalRequestId: WithdrawalRequestId): Promise<void>;
    requestWithdrawal(amount: Amount, provider: Variant_imePay_khalti, identifier: string, payoutName: string): Promise<WithdrawalRequestId>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    verifyTournament(tournamentId: TournamentId): Promise<void>;
}
import type { Amount as _Amount, TopUpRequest as _TopUpRequest, TopUpRequestId as _TopUpRequestId, UserProfile as _UserProfile, UserRole as _UserRole, WalletTransaction as _WalletTransaction, WalletTransactionId as _WalletTransactionId, WithdrawalRequest as _WithdrawalRequest, WithdrawalRequestId as _WithdrawalRequestId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveTopUpRequest(arg0: TopUpRequestId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveTopUpRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveTopUpRequest(arg0);
            return result;
        }
    }
    async approveWithdrawalRequest(arg0: WithdrawalRequestId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawalRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawalRequest(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createTopUpRequest(arg0: Amount): Promise<TopUpRequestId> {
        if (this.processError) {
            try {
                const result = await this.actor.createTopUpRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTopUpRequest(arg0);
            return result;
        }
    }
    async createTournament(arg0: string, arg1: Amount): Promise<TournamentId> {
        if (this.processError) {
            try {
                const result = await this.actor.createTournament(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTournament(arg0, arg1);
            return result;
        }
    }
    async getBalance(): Promise<Amount> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalance();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopUpHistory(): Promise<Array<TopUpRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopUpHistory();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopUpHistory();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopUpRequests(): Promise<Array<TopUpRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopUpRequests();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopUpRequests();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionHistory(): Promise<Array<WalletTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistory();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistory();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWithdrawalRequests(): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWithdrawalRequests();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWithdrawalRequests();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinTournament(arg0: TournamentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.joinTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinTournament(arg0);
            return result;
        }
    }
    async markWithdrawalRequestCompleted(arg0: WithdrawalRequestId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markWithdrawalRequestCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markWithdrawalRequestCompleted(arg0);
            return result;
        }
    }
    async requestWithdrawal(arg0: Amount, arg1: Variant_imePay_khalti, arg2: string, arg3: string): Promise<WithdrawalRequestId> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0, to_candid_variant_n19(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0, to_candid_variant_n19(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async verifyTournament(arg0: TournamentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyTournament(arg0);
            return result;
        }
    }
}
function from_candid_TopUpRequest_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TopUpRequest): TopUpRequest {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_WalletTransaction_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalletTransaction): WalletTransaction {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalRequest_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalRequest): WithdrawalRequest {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _WalletTransactionId;
    transactionType: {
        withdrawalRequest: null;
    } | {
        topUp: null;
    } | {
        deposit: null;
    } | {
        withdrawal: null;
    } | {
        prize: null;
    };
    userId: Principal;
    createdAt: bigint;
    amount: _Amount;
}): {
    id: WalletTransactionId;
    transactionType: Variant_withdrawalRequest_topUp_deposit_withdrawal_prize;
    userId: Principal;
    createdAt: bigint;
    amount: Amount;
} {
    return {
        id: value.id,
        transactionType: from_candid_variant_n14(_uploadFile, _downloadFile, value.transactionType),
        userId: value.userId,
        createdAt: value.createdAt,
        amount: value.amount
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _WithdrawalRequestId;
    status: {
        pending: null;
    } | {
        completed: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    payoutIdentifier: string;
    userId: Principal;
    createdAt: bigint;
    amount: _Amount;
    payoutName: string;
    paymentProvider: {
        imePay: null;
    } | {
        khalti: null;
    };
}): {
    id: WithdrawalRequestId;
    status: Variant_pending_completed_approved_rejected;
    payoutIdentifier: string;
    userId: Principal;
    createdAt: bigint;
    amount: Amount;
    payoutName: string;
    paymentProvider: Variant_imePay_khalti;
} {
    return {
        id: value.id,
        status: from_candid_variant_n18(_uploadFile, _downloadFile, value.status),
        payoutIdentifier: value.payoutIdentifier,
        userId: value.userId,
        createdAt: value.createdAt,
        amount: value.amount,
        payoutName: value.payoutName,
        paymentProvider: from_candid_variant_n10(_uploadFile, _downloadFile, value.paymentProvider)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TopUpRequestId;
    status: {
        pending: null;
    } | {
        completed: null;
    };
    payoutIdentifier: string;
    userId: Principal;
    createdAt: bigint;
    amount: _Amount;
    paymentProvider: {
        imePay: null;
    } | {
        khalti: null;
    };
    transactionId: string;
}): {
    id: TopUpRequestId;
    status: Variant_pending_completed;
    payoutIdentifier: string;
    userId: Principal;
    createdAt: bigint;
    amount: Amount;
    paymentProvider: Variant_imePay_khalti;
    transactionId: string;
} {
    return {
        id: value.id,
        status: from_candid_variant_n9(_uploadFile, _downloadFile, value.status),
        payoutIdentifier: value.payoutIdentifier,
        userId: value.userId,
        createdAt: value.createdAt,
        amount: value.amount,
        paymentProvider: from_candid_variant_n10(_uploadFile, _downloadFile, value.paymentProvider),
        transactionId: value.transactionId
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    imePay: null;
} | {
    khalti: null;
}): Variant_imePay_khalti {
    return "imePay" in value ? Variant_imePay_khalti.imePay : "khalti" in value ? Variant_imePay_khalti.khalti : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    withdrawalRequest: null;
} | {
    topUp: null;
} | {
    deposit: null;
} | {
    withdrawal: null;
} | {
    prize: null;
}): Variant_withdrawalRequest_topUp_deposit_withdrawal_prize {
    return "withdrawalRequest" in value ? Variant_withdrawalRequest_topUp_deposit_withdrawal_prize.withdrawalRequest : "topUp" in value ? Variant_withdrawalRequest_topUp_deposit_withdrawal_prize.topUp : "deposit" in value ? Variant_withdrawalRequest_topUp_deposit_withdrawal_prize.deposit : "withdrawal" in value ? Variant_withdrawalRequest_topUp_deposit_withdrawal_prize.withdrawal : "prize" in value ? Variant_withdrawalRequest_topUp_deposit_withdrawal_prize.prize : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_completed_approved_rejected {
    return "pending" in value ? Variant_pending_completed_approved_rejected.pending : "completed" in value ? Variant_pending_completed_approved_rejected.completed : "approved" in value ? Variant_pending_completed_approved_rejected.approved : "rejected" in value ? Variant_pending_completed_approved_rejected.rejected : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
}): Variant_pending_completed {
    return "pending" in value ? Variant_pending_completed.pending : "completed" in value ? Variant_pending_completed.completed : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WalletTransaction>): Array<WalletTransaction> {
    return value.map((x)=>from_candid_WalletTransaction_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalRequest>): Array<WithdrawalRequest> {
    return value.map((x)=>from_candid_WithdrawalRequest_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TopUpRequest>): Array<TopUpRequest> {
    return value.map((x)=>from_candid_TopUpRequest_n7(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_imePay_khalti): {
    imePay: null;
} | {
    khalti: null;
} {
    return value == Variant_imePay_khalti.imePay ? {
        imePay: null
    } : value == Variant_imePay_khalti.khalti ? {
        khalti: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
